### ISSUE TITLE
ImportError: cannot import name 'constants'

### ISSUE THREAD

**Issue by zonaut** [hsmade/certbot-dns-transip#21]
Hi, this is more a question. After upgrading with `pip3 install --upgrade certbot-dns-transip --force-reinstall` I get an error that an import fails with the following stacktrace.
Is there something I need to do when upgrading a python package?

2020-03-22 09:19:31,449:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/main.py", line 1317, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/plugins/disco.py", line 210, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/plugins/disco.py", line 54, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 16, in <module>
    from certbot import constants as core_constants
ImportError: cannot import name 'constants'
2020-03-22 09:19:31,449:ERROR:certbot._internal.log:An unexpected error occurred:

**Comment by zonaut** [comment]
Ok, fixed it by doing the following, still don't understand why.

```
apt remove python-certbot-nginx
rm -rf /usr/local/lib/python3.6/dist-packages/certbot*
rm -rf /usr/lib/python3/dist-packages/certbot*
apt install -y python-certbot-nginx
pip3 install --upgrade certbot-dns-transip --force-reinstall
```

**Comment by hsmade** [comment]
Seems like an issue with the nginx plugin, not this one. Nice that you managed to fix it though.
