### ISSUE TITLE
Type not found: '(array, http://www.w3.org/2001/XMLSchema, )'

### ISSUE THREAD

**Issue by KajdeMunter** [hsmade/certbot-dns-transip#22]
Hello, i'm experiencing the following error:

```
$ certbot certonly --agree-tos -d domain.com -d *.domain.com -a certbot-dns-transip:dns-transip --certbot-dns-transip:dns-transip-credentials /etc/letsencrypt/transip.ini --certbot-dns-transip:dns-transip-propagation-seconds 240 --expand -n


Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-transip:dns-transip, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for domain.com
dns-01 challenge for domain.com
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot/_internal/error_handler.py", line 125, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/dist-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_transip/dns_transip.py", line 71, in _cleanup
    self._get_transip_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_transip/dns_transip.py", line 90, in _get_transip_client
    return _TransipClient(username=username, key_file=key_file)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_transip/dns_transip.py", line 98, in __init__
    self.domain_service = DomainService(login=username, private_key_file=key_file)
  File "/usr/local/lib/python2.7/dist-packages/transip/service/domain.py", line 12, in __init__
    super(DomainService, self).__init__('DomainService', *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/transip/client.py", line 90, in __init__
    self.soap_client = SudsClient(self.url, doctor=doc, **suds_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 122, in __init__
    sd = ServiceDefinition(self.wsdl, s)
  File "/usr/local/lib/python2.7/dist-packages/suds/servicedefinition.py", line 58, in __init__
    self.addports()
  File "/usr/local/lib/python2.7/dist-packages/suds/servicedefinition.py", line 86, in addports
    method = (m.name, binding.param_defs(m))
  File "/usr/local/lib/python2.7/dist-packages/suds/bindings/rpc.py", line 35, in param_defs
    return self.bodypart_types(method)
  File "/usr/local/lib/python2.7/dist-packages/suds/bindings/binding.py", line 379, in bodypart_types
    raise TypeNotFound(query.ref)
TypeNotFound: Type not found: '(array, http://www.w3.org/2001/XMLSchema, )'
```

Happens with both python 2 and 3, as well as a renewal command, using the following pip packages:
```
certbot==1.2.0
certbot-dns-transip==0.2.6
```

**Comment by KajdeMunter** [comment]
I see now that it should be fixed in https://github.com/benkonrath/transip-api/issues/60, problem is on my end.

**Comment by hsmade** [comment]
Thx for the update!
