### ISSUE TITLE
Certbot does not honor Proxy variables

### ISSUE THREAD

**Issue by damige** [hsmade/certbot-dns-transip#39]
On Debian 11:
Proxy has been set as enviroment variable:
```
http_proxy="http://x,x,x,x:yyyy/"
https_proxy="http://x,x,x,x:yyyy/"
HTTP_PROXY="http://x,x,x,x:yyyy/"
HTTPS_PROXY="http://x,x,x,x:yyyy/"
```

The connection to: acme-v02.api.letsencrypt.org honors this.
The connection to: api.transip.nl does not

```
Encountered exception during recovery: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: /v6/auth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b0c402ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: /v6/auth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b0c487d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
I would have expected all connections to honor proxy settings.

**Comment by hsmade** [comment]
Thanks, I'll have a look!

**Comment by hsmade** [comment]
The code is using the transip python library, which in turn uses requests, so I'd say the env vars should just work.
I'll try to see if I can reproduce your issue locally.

**Comment by damige** [comment]
Thats interesting, in my case i observed that the firewall was dropping direct traffic to port 443(api.transip.nl). Let me block this again and see.

**Comment by damige** [comment]
I run this script:

```
declare -a web=("www.a.b" "www.c.d" "www.e.f" "www.g.h")

for website in "${web[@]}"
   do
       certbot certonly -n -d $website -a dns-transip --dns-transip-credentials /[dir]/transip.ini --dns-transip-propagation-seconds 240 --agree-tos -m certbot@a.b  --work-dir /[dir]/test --logs-dir /[dir]/test --config-dir /[dir]/config
   done
```

Then this happens:
`Encountered exception during recovery: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: /v6/auth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8811575b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`


```
And the firewall shows:
  | Jan 25 18:23:25 | BRIDGELANTRUST | 10.9.8.200:59888 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:23:24 | BRIDGELANTRUST | 10.9.8.200:59888 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:23:17 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:23:01 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:22:53 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:22:49 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:22:47 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
  | Jan 25 18:22:46 | BRIDGELANTRUST | 10.9.8.200:59886 | 37.97.254.6:443 | TCP:S
```

**Comment by damige** [comment]
edit: **/v6/auth**  On the off chance this referred to ipv6, i disabled ipv6 completly on my distro (ipv6 not supported by ISP). No difference, same error.

**Comment by hsmade** [comment]
Odd. What does `set|grep -i proxy` look like?

**Comment by damige** [comment]
```
set|grep -i proxy
HTTPS_PROXY=http://x.x.x.x:yyyy/
HTTP_PROXY=http://x.x.x.x:yyyy/
http_proxy=http://x.x.x.x:yyyy/
https_proxy=http://x.x.x.x:yyyy/
```

**Comment by hsmade** [comment]
which version of certbot, the transip plugin and requests do you have installed?

**Comment by damige** [comment]
```
certbot --version 
certbot 1.22.0
```
Did an install of certbot-dns-transip yesterday through pip, how do i check the transip plugin version?

**Comment by hsmade** [comment]
`pip freeze` shows all installed versions

**Comment by damige** [comment]
```
certbot-dns-transip==0.4.3
python-transip==0.5.0
```

**Comment by hsmade** [comment]
And requests?

**Comment by damige** [comment]
sorry
```

requests==2.25.1
requests-toolbelt==0.9.1
```

**Comment by hsmade** [comment]
Can you please try to see if this returns 200 or an error?
```bash
python -c 'import requests; print(requests.get("https://api.transip.nl").status_code)'

```

**Comment by hsmade** [comment]
and if that's an error, try with:
```bash
HTTPS_PROXY=http://localhost:3128 python -c 'import requests; print(requests.get("https://api.transip.nl").status_code)'
```
Where you replace localhost:3128 with your proxy details?

**Comment by hsmade** [comment]
Can you check if this give you a 404 or the proxy error?
```bash
python -c 'import transip; transip.TransIP(login="<your username>", private_key_file="transip.key").domains.get("example.com")'
```

Also, to be sure, you're using python3, right?

**Comment by damige** [comment]
```
python --version
Python 3.9.2
```
When i do this: (with the correct user and file) 
`python -c 'import transip; transip.TransIP(login="<your username>", private_key_file="transip.key").domains.get("example.com")'`

I observe the same drops on the firewall (so non proxied)

**Comment by damige** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe7d3deddc0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: /v6/auth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7d3deddc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/transip/__init__.py", line 87, in __init__
    self._set_auth_info()
  File "/usr/local/lib/python3.9/dist-packages/transip/__init__.py", line 256, in _set_auth_info
    self._access_token = self._request_access_token()
  File "/usr/local/lib/python3.9/dist-packages/transip/__init__.py", line 185, in _request_access_token
    response: requests.Response = self.session.send(prepped)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: /v6/auth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7d3deddc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by hsmade** [comment]
Right, so it's a problem with that library indeed. Let me do a bit of reading through the code, see if we can do a PR with that library.

**Comment by hsmade** [comment]
Does this work? This is basically what the transip lib is doing..
```bash
python -c 'import requests; session=requests.Session(); session.send(session.prepare_request(requests.Request("POST", "https://api.transip.nl", headers={"User-Agent":"itsme"}, json={})))'
```

**Comment by damige** [comment]
Sorry, same error

```
 python -c 'import requests; session=requests.Session(); session.send(session.prepare_request(requests.Request("POST", "https://api.transip.nl", headers={"User-Agent":"itsme"}, json={})))'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7feee881a670>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feee881a670>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.transip.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feee881a670>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by hsmade** [comment]
What's the output of `pip freeze |grep urllib3`? It seems it's pretty deep, this issue..

**Comment by damige** [comment]
```
pip freeze |grep urllib3
urllib3==1.26.5
```

**Comment by hsmade** [comment]
It's weird, I can't reproduce it in docker, with the same versions of requests and urllib3.
You don't have anything else in the proxy var than `HTTPS_PROXY=http://localhost:3128`? So no username, password, https?

**Comment by damige** [comment]
no just IP+port

**Comment by damige** [comment]
Thanks for your time, it seems to work now!

I went nuclear on my system, i removed all the pip packages, then those that could not be removed i removed from apt. 
After removing them i reinstalled the packeges and reinstalled certbot-dns-transip.
certbot complained about it not having python-transip. So i installed that.
Then it complained it was version 0.6.0 so i reinstalled it as 0.5.0. (which it was originally also)

The proxy server now logs:
```
Date | IP | Status | Address | User | Destination
25.01.2022 22:04:01 | 10.9.8.200 | TCP_TUNNEL/200 | api.transip.nl:443 | - | 37.97.254.6

```
And all is fine.
This is wierd to me as i never did anything with those packages before so i have no idea how something could have become broken..

Thanks again!

**Comment by hsmade** [comment]
Funny things indeed. This is why I prefer to use docker with python software, as the dependencies of other packages often screw up neighbours.

Nice that it worked out :)

**Comment by damige** [comment]
Good bit of advice i will look into docker in the future! thanks!
