### ISSUE TITLE
Error installing certs

### ISSUE THREAD

**Issue by wimjongman** [hsmade/certbot-dns-transip#4]
Hi, the installation fails with the error below. This is my command

certbot certonly -d *.gravity.zone,gravity.zone -a certbot-dns-transip:dns-transip --certbot-dns-transip:dns-transip-credentials transip.ini --certbot-dns-transip:dns-transip-propagation-seconds 240

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-transip:dns-transip, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for gravity.zone
Unsafe permissions on credentials configuration file: transip.ini
Cleaning up challenges
Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 132, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 65, in _perform
    self._get_transip_client().add_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 110, in add_txt_record
    domain = self._find_domain(domain_name)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 197, in _find_domain
    domains = self.domain_service.get_domain_names()
  File "/usr/local/lib/python3.5/dist-packages/transip/service/domain.py", line 48, in get_domain_names
    return self._simple_request('getDomainNames')
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 172, in _simple_request
    cookie = self.build_cookie(mode=kwargs.get('mode', MODE_RO), method=method, parameters=args)
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 155, in build_cookie
    signature = self._sign(message_to_sign)
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 81, in _sign
    privkey = rsa.PrivateKey.load_pkcs1(keydata)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 118, in load_pkcs1
    return method(keyfile)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 560, in _load_pkcs1_pem
    return cls._load_pkcs1_der(der)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 495, in _load_pkcs1_der
    key = cls(*as_ints)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Sequence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 316, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 70, in _cleanup
    self._get_transip_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 157, in del_txt_record
    domain = self._find_domain(domain_name)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_transip/dns_transip.py", line 197, in _find_domain
    domains = self.domain_service.get_domain_names()
  File "/usr/local/lib/python3.5/dist-packages/transip/service/domain.py", line 48, in get_domain_names
    return self._simple_request('getDomainNames')
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 172, in _simple_request
    cookie = self.build_cookie(mode=kwargs.get('mode', MODE_RO), method=method, parameters=args)
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 155, in build_cookie
    signature = self._sign(message_to_sign)
  File "/usr/local/lib/python3.5/dist-packages/transip/client.py", line 81, in _sign
    privkey = rsa.PrivateKey.load_pkcs1(keydata)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 118, in load_pkcs1
    return method(keyfile)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 560, in _load_pkcs1_pem
    return cls._load_pkcs1_der(der)
  File "/usr/local/lib/python3.5/dist-packages/rsa/key.py", line 495, in _load_pkcs1_der
    key = cls(*as_ints)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Sequence'
An unexpected error occurred:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Sequence'
Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by hsmade** [comment]
Unsafe permissions on credentials configuration file: transip.ini

chmod 600 transip.ini

**Comment by wimjongman** [comment]
Thanks, Marcel, that fixed it.

**Comment by BartVB** [comment]
Thanks!
Ran into the same problem, converting the key fixed it.

**Comment by hsmade** [comment]
Updated the docs to reflect this requirement
