### ISSUE TITLE
Cannot find private key

### ISSUE THREAD

**Issue by MartijnStraatman** [hsmade/certbot-dns-transip#8]
Hi,

I am trying to run the docker container, but it complains there is no private key. I have mounted as a volume. Also permissions are ok!

docker run -i -v /etc/letsencrypt/transip.ini:/transip.ini -v /etc/letsencrypt/transip-rsa.key:/transip-rsa.key hsmade/certbot-transip certbot certonly --cert-name "<name>" -d "<domain>" -a certbot-dns-transip:dns-transip --certbot-dns-transip:dns-transip-credentials transip.ini  --certbot-dns-transip:dns-transip-propagation-seconds 240 --server https://acme-staging-v02.api.letsencrypt.org/directory -n -m <mail> --agree-tos --test-cert",

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 316, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 70, in _cleanup
    self._get_transip_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 157, in del_txt_record
    domain = self._find_domain(domain_name)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 197, in _find_domain
    domains = self.domain_service.get_domain_names()
  File "/usr/local/lib/python2.7/site-packages/transip/service/domain.py", line 48, in get_domain_names
    return self._simple_request('getDomainNames')
  File "/usr/local/lib/python2.7/site-packages/transip/client.py", line 172, in _simple_request
    cookie = self.build_cookie(mode=kwargs.get('mode', MODE_RO), method=method, parameters=args)
  File "/usr/local/lib/python2.7/site-packages/transip/client.py", line 155, in build_cookie
    signature = self._sign(message_to_sign)
  File "/usr/local/lib/python2.7/site-packages/transip/client.py", line 89, in _sign
    raise RuntimeError('The private key does not exist.')
RuntimeError: The private key does not exist.
An unexpected error occurred:
RuntimeError: The private key does not exist.

**Comment by hsmade** [comment]
What's the contents of `transip.ini`?

**Comment by MartijnStraatman** [comment]
yes fixed, thanks. Do you sometimes experience issues with deleting txt record when serving multiple domains for one certificate?

Successfully added TXT record
Successfully added TXT record
Successfully added TXT record
Waiting 240 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Removing TXT record with name: _acme-challenge.example1.qref
Removing TXT record with name: _acme-challenge.example2.qref
Removing TXT record with name: _acme-challenge.example3.qref
Failed authorization procedure. example2.qref.rijksapps.nl (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for ....

**Comment by hsmade** [comment]
Hmm no, and I actually have all my domains in one cert.
